name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-test
    steps:
      - uses: actions/checkout@v3
      - uses: npm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install --frozen-lockfile
      - run: npm run lint && npm run build
